### PR TITLE
Add support for COBOL inline comments

### PR DESCRIPTION
**Pull request by vasilescur**
Simply adding comment delimiter "*>" to language ID "COBOL" in the parser.

### CODE REVIEW

**Comment by aaron-bond** [comment]
Thanks for this. It probably needs the language activation event too. I'll get it reviewed and merged in this weekend.

**Comment by danielreiser** [comment]
@vasilescur thanks for your contribution. would you mind updating the package.json `activationEvents` and add COBOL to the readme.md :)?

**Comment by vasilescur** [comment]
Okay, I updated `package.json` and `README.md` as requested.

**Comment by aaron-bond** [comment]
Thanks for the contribution, this has been merged in manually :)

**Pull request closed without merging**
