### PR TITLE
Added the right delimiter for modern fortran

### PR DESCRIPTION
**Pull request by gnikit**
This merge solves the issue highlighted in #185 .
Might be worth adding some regression testing like the one already in place for this type of fortran comments.

### CODE REVIEW

**Comment by GNikit** [comment]
I also updated the buildbot because seeing it fail annoyed me.

**Comment by aaron-bond** [comment]
Thanks for the PR. Could you add samples for the new formats in the `test/samples` folder?

Also, could you check the indentation on the case..switch statement to keep it consistent with what's already there?

**Comment by GNikit** [comment]
I added some example code for new and old fortran and made the indentation consistent.
Does it look okay now?

**Comment by GNikit** [comment]
This merge should probably be postponed for a bit, since the implemented changes cause incorrect coloring of strings`print*, "something important!!! something else"`. I'll have a look during to see if there is an easy fix.

**Comment by breengles** [comment]
> This merge should probably be postponed for a bit, since the implemented changes cause incorrect coloring of strings`print*, "something important!!! something else"`. I'll have a look during to see if there is an easy fix.

Hi, no news about that for FreeForm? 🤔

**Comment by GNikit** [comment]
Yeah, this is not fortran specific, so the PR is fine. I believe that in any language, if the delimiter character is used within a comment followed by one of the reserved characters, the same behaviour listed above will occur.
e.g. in Python
`# Comment #! this is red`,
`"""
Comment #! this is red
"""` 
or
`print("#! this is red")`

I believe this would require a bit of a rewrite of the extension so as to escape string chars in all supported languages with comment characters in them.

**Comment by GNikit** [comment]
I made a new issue addressing this string highlighting behaviour  #202 .

**Comment by gnikit** [comment]
Hi @aaron-bond any chance we could merge this to master?

**Comment by Arsennnic** [comment]
@gnikit your commits seems useful. 
Since @aaron-bond has not merged your commits, how could I manually install your modified plugin?

**Comment by gnikit** [comment]
> @gnikit your commits seem useful.
> Since @aaron-bond has not merged your commits, how could I manually install your modified plugin?

The best solution would be for someone with write access to this repo to merge this branch and publish a new version of the extension, but for some reason this has yet to happen.

You could go and manually edit `parser.js`, where the extension is installed, with the code that I added in `parser.ts` but beware that if you have extension syncing enabled these changes will be overwritten whenever the extensions are synced with your GitHub/Microsoft account. So really the only solution is for @aaron-bond to merge this to master.

@Arsennnic one more thing I should probably point out about this extension and Fortran code is that `!!` in Fortran is used by default in Doxygen documentation as continuation characters. Using this extension with Doxygen-styled docstrings will cause them to be highlighted in bright red, which can be a bit annoying for some.

**Comment by Arsennnic** [comment]
> 
> 
> > @gnikit your commits seem useful.
> > Since @aaron-bond has not merged your commits, how could I manually install your modified plugin?
> 
> The best solution would be for someone with write access to this repo to merge this branch and publish a new version of the extension, but for some reason this has yet to happen.
> 
> You could go and manually edit `parser.js`, where the extension is installed, with the code that I added in `parser.ts` but beware that if you have extension syncing enabled these changes will be overwritten whenever the extensions are synced with your GitHub/Microsoft account. So really the only solution is for @aaron-bond to merge this to master.
> 
> @Arsennnic one more thing I should probably point out about this extension and Fortran code is that `!!` in Fortran is used by default in Doxygen documentation as continuation characters. Using this extension with Doxygen-styled docstrings will cause them to be highlighted in bright red, which can be a bit annoying for some.

Thanks! I have managed to do this. I wrote this down for others who may need help.
In `parser.js` I added following lines for `setDelimiter(languageCode)`:
```js
case "FortranFreeForm":
  this.delimiter = "!";
  break;
case "fortran_fixed-form":
  this.delimiter = "c";
  break;
```

**Pull request closed without merging**
