### PR TITLE
Possibility to add your own languages settings

### PR DESCRIPTION
**Pull request by vitalyruhl**
Hi, I use a custom Language (intouch) and needed your supper extension to go work.
now i addet  this in package.json

```js
"properties": {
				"better-comments.UseCustomDefined": {
					"type": "boolean",
					"description": "Use custom defined comment definition",
					"default": true
				},
				"better-comments.CustomDefinedComment": {
					"type": "array",
					"description": "Tags which are used to color the comments. Changes require a restart of VS Code to take effect",
					"default": [
						{
							"Language":"intouch",
							"singleLine":"{",
							"start": "{",
							"end": "}"
						}
					]
				},
...
```
I don't know why it shows all text s changed...

And then you can add some languages into extension without recompile it.

Screenshot_1
.
**Wouldn't it be better to configure all languages like this?**

### CODE REVIEW

**Comment by aaron-bond** [comment]
Hi, I'm working on a branch which allows support for all languages and could really use some help testing it if you're interested? With the code here, your language should work as expected:
https://github.com/aaron-bond/better-comments/tree/all-languages

**Comment by vitalyruhl** [comment]
Hi, it's great. I will test it on weekend.

**Comment by vitalyruhl** [comment]
Hi - I try it today. And it works great! A good Idea to get strings from the Language itself!!!
Screenshot_2
But a question, why do you need activating section:
Screenshot_3
There is my language not included, but it works. You can activate it on start - this 10ms more on start is not important?!

**Comment by aaron-bond** [comment]
Yeah I'll be removing the activation events

**Pull request closed without merging**
