### PR TITLE
add ansible language support

### PR DESCRIPTION
**Pull request by matuck**

### CODE REVIEW

**Comment by aaron-bond** [comment]
I think the branch I'm currently working on should solve this request.

If you're interested, I could really use some help testing:
https://github.com/aaron-bond/better-comments/tree/all-languages

**Comment by matuck** [comment]
I will give it some testing

**Comment by aaron-bond** [comment]
Many thanks!

**Comment by matuck** [comment]
I have tested across a few languages I use and this does seem to do the trick.  Ansible,YAML, C#, PHP, Python
Will continue to test to make sure i dont run into problem but seems to work good.

**Comment by aaron-bond** [comment]
Excellent. I really appreciate that :) this should go live some time in the next month once I'm happy I haven't broken anything too significant.

**Pull request closed without merging**
