### PR TITLE
Added support to all languages

### PR DESCRIPTION
**Pull request by edgardmessias**
How it works:
* Generate a map of language configuration map, base on all extensions
* If not found a language in `setDelimiter`, try load configuration from extension

### CODE REVIEW

**Comment by aaron-bond** [comment]
This is a really interesting idea. How does the comment start and end syntax get picked up? Does it account for single line and block?

**Comment by edgardmessias** [comment]
Abstract: 
Each `language-configuration.json` may contains:
`comments.blockComment` - The begin and end token used to mark a block comment. Used by the 'Toggle Block Comment' command.
`comments.lineComment` - The begin token used to mark a line comment. Used by the 'Add Line.

You can read more here: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

**Comment by edgardmessias** [comment]
I can modify to check first line, using the `contributes.languages.firstLine`

**Comment by jasonlyle88** [comment]
@aaron-bond @edgardmessias It looks like there are a lot of language requests sitting in the PR queue for better comments. I originally came to github to request language support for plsql, only to see it was already supported. But I'm using a different oracle PL/SQL package to add the language, thus the language code for my files is "oraclesql" and doesn't get parsed by better comments. If this is a viable approach, is there a chance of this getting integrated into better comments any time soon? Seems like it would solve a lot of work on your end!

**Comment by edgardmessias** [comment]
Closed in favor of #302

**Pull request closed without merging**
