### PR TITLE
Add FIXME and HACK to default tags

### PR DESCRIPTION
**Pull request by arvigeus**
I think these are sane defaults

### CODE REVIEW

**Comment by aaron-bond** [comment]
I like the idea for these, but I'm wondering if these are  covered enough by the TODO?
I intended the defaults to be more of a guideline than an actual pre-defined list. I expected most would add their own in their personal configurations. Do you see much use of FIXME and HACK in comments in the wild?

**Comment by arvigeus** [comment]
The way I see it, TODO is for adding code, FIXME is for fixing existing code, HACK is for ugly code that works. You are right that adding all existing codewords could be an overkill. It's your call whether your project needs this or not. Since it is easy to add keywords, not including those is fine.
Another idea that comes to my mind is to add a special case, like /[A-Z]+\:/ (capital letters followed by : ) to easy color all cases not matched

**Comment by aaron-bond** [comment]
There's currently a FR for having multiple tags match to one style so I think as part of that expansion I'll add support for these :)

**Comment by dvdgsng** [comment]
Would be nice to have this merged. While there is always the possibility to implement your own templates quite easily, I do agree that this extension would gain a lot from supporting more code tags that are commonly used.

There are more code tags that one could implement. Some suggestions:
- XXX
- BUG
- TRICKY
- WARNING

Even more see here: https://www.python.org/dev/peps/pep-0350/#mnemonics

**Comment by aaron-bond** [comment]
@dvdgsng are those tags specific to python? I don't think I've ever seen any of those used as a standard in comments before.

I think I agree that these are sane comment tags to add, but I don't want the extension to be too opinionated on which coding standards you adhere to. I think that's if I was going to add anything like what you have there, I'd rather do it in some form of "Suggested settings" file which could be copied / pasted into your own config (depending on preferred language).

Would that fit the same requirement?

**Comment by dvdgsng** [comment]
@aaron-bond Hi. Yes, that python list is extensive, but they are not Python specific, not opinionated and can be used with any language. I linked it as an example what *could* be supported. I've never seen most of them in the wild either, in fact one could debate the usefulness of quite a few of them :).

I like your suggestion of a "Suggested Settings" list. Doesn't need to be a separate file, another entry in the README or wiki should work, too. README would be best, imho, since it is easily visible.

**Comment by robsonpeixoto** [comment]
FIXME is very common. Some examples:
- https://github.com/torvalds/linux/search?q=FIXME&unscoped_q=FIXME
- https://github.com/python/cpython/search?q=FIXME&unscoped_q=FIXME
- https://github.com/nodejs/node/search?q=FIXME&unscoped_q=FIXME

**Pull request closed without merging**
