### PR TITLE
Enable your extension to run on VS Code for the web

### PR DESCRIPTION
**Pull request by tanhakabir**
Hello @aaron-bond 👋

I'm part of the VS Code team and we recently launched VS Code for the web with [github.dev](https://docs.github.com/en/codespaces/developing-in-codespaces/web-based-editor)! You can read the full guide for extension authors creating and migrating extensions here: [Web Extensions
](https://code.visualstudio.com/api/extension-guides/web-extensions)

In hopes to help you migrate I helped make the changes necessary to make your extensions work on the web.

The changes I made:
- Added webpack bundling to bundle your extension into 1 JavaScript file for the web
- Added the compile scripts for webpack to your `package.json`
- Added the necessary dependencies for bundling
- Added the `browser` entry point to your `package.json` to link to the web-friendly compiled extension

### CODE REVIEW

**Comment by isidorn** [comment]
Hi, Isidor here, a PM from VS Code 👋
We would really like to have better-comments available in VS Code for Web.
@aaron-bond is there something blocking this PR from being merged? Can we help somehow with the PR review process?
Thanks a lot!

**Comment by lorenzocorallo** [comment]
@aaron-bond Would you consider these changes to make this extension available for VS Code Web? This is the best extension for comments and it's an important missing in my opinion. Seems that it isn't that much code, so it should be easily integrated.

**Comment by LaCocoRoco** [comment]
@tanhakabir
 
1. cloned your better-comment web branch
2. got error with vsce: "error:0308010C:digital envelope routines::unsupported"
3. updated webpack
4. packing worked as expected 
5. installed the vsix extension in code server
6. got error: "This extension is disabled because it is not supported in code-server for the Web"

Did i something wrong?
Could you give me some advise or confirm this problem?

**Comment by aaron-bond** [comment]
Hi @tanhakabir, sorry it's taken me so long to take a look at this. Is the process still the same to enable for the web? Am I safe to update / merge this PR?

**Comment by isidorn** [comment]
@aaron-bond thank you for your response. Yes, the process is the same. However I see the branch has conflicts.
Maybe @tanhakabir can resolve those and verify it is good for merging?

**Comment by LaCocoRoco** [comment]
Can't this issue be closed because the extension can be installed on code-server, gitpod or codespace?
Or did i miss something?

**Comment by aaron-bond** [comment]
Many thanks for this PR @tanhakabir - I'll push a release this evening.

**Pull request merged**
